/**
 * Clean, robust printer and export utility for AI Practice Coach Assessments.
 * Supports direct document printing, standalone HTML report download,
 * structured text export, and clipboard copying.
 */

export interface AssessmentData {
  date: string;
  time: string;
  analysis: string;
  sessionCount?: number;
}

/**
 * Generates an isolated, beautiful HTML document string for printing
 */
export function generateAssessmentHtml(
  assessment: AssessmentData,
  autoPrintOnLoad = false
): string {
  const escapedText = assessment.analysis
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  const currentDate = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Guitar Practice Tracker - AI Assessment (${assessment.date})</title>
  <style>
    @page {
      size: letter portrait;
      margin: 16mm;
    }
    * {
      box-sizing: border-box;
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      color: #0f172a;
      background: #ffffff;
      margin: 0;
      padding: 24px;
      line-height: 1.6;
      font-size: 13.5px;
    }
    .report-card {
      max-width: 800px;
      margin: 0 auto;
    }
    .header {
      border-bottom: 2.5px solid #4338ca;
      padding-bottom: 14px;
      margin-bottom: 20px;
    }
    .header-top {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
    }
    .brand-title {
      font-size: 24px;
      font-weight: 800;
      color: #1e1b4b;
      margin: 0 0 4px 0;
      letter-spacing: -0.02em;
    }
    .brand-sub {
      font-size: 13px;
      font-weight: 500;
      color: #475569;
      margin: 0;
    }
    .badge {
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      background: #e0e7ff;
      color: #3730a3;
      padding: 4px 12px;
      border-radius: 9999px;
      border: 1px solid #c7d2fe;
    }
    .meta-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 12px;
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 12px 16px;
      margin-bottom: 22px;
    }
    .meta-item {
      display: flex;
      flex-direction: column;
    }
    .meta-label {
      font-size: 10px;
      text-transform: uppercase;
      letter-spacing: 0.06em;
      font-weight: 700;
      color: #64748b;
    }
    .meta-val {
      font-size: 14px;
      font-weight: 700;
      color: #0f172a;
      margin-top: 3px;
    }
    .analysis-container {
      background: #ffffff;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 22px 24px;
      white-space: pre-wrap;
      word-wrap: break-word;
      font-size: 13.5px;
      line-height: 1.7;
      color: #1e293b;
    }
    .footer {
      margin-top: 32px;
      padding-top: 14px;
      border-top: 1px solid #e2e8f0;
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-size: 11px;
      color: #94a3b8;
    }
    @media print {
      body {
        padding: 0;
      }
      .no-print {
        display: none !important;
      }
    }
  </style>
  ${autoPrintOnLoad ? "<script>window.onload = function() { setTimeout(function() { window.print(); }, 200); };</script>" : ""}
</head>
<body>
  <div class="report-card">
    <div class="header">
      <div class="header-top">
        <div>
          <h1 class="brand-title">Guitar Practice Tracker</h1>
          <p class="brand-sub">AI Practice Coach Progress Assessment Report</p>
        </div>
        <div class="badge">Official Report</div>
      </div>
    </div>

    <div class="meta-grid">
      <div class="meta-item">
        <span class="meta-label">Assessment Date</span>
        <span class="meta-val">${assessment.date}</span>
      </div>
      <div class="meta-item">
        <span class="meta-label">Recorded Time</span>
        <span class="meta-val">${assessment.time}</span>
      </div>
      <div class="meta-item">
        <span class="meta-label">Practice Data Evaluated</span>
        <span class="meta-val">${assessment.sessionCount !== undefined ? `${assessment.sessionCount} Sessions` : "Full History"}</span>
      </div>
    </div>

    <div class="analysis-container">${escapedText}</div>

    <div class="footer">
      <span>Generated by Guitar Practice Tracker AI Coach</span>
      <span>Printed on ${currentDate}</span>
    </div>
  </div>
</body>
</html>`;
}

/**
 * Downloads a standalone HTML file that can be opened and printed in any browser
 */
export function downloadAssessmentHtml(assessment: AssessmentData): void {
  const html = generateAssessmentHtml(assessment, true);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const filename = `guitar-practice-assessment-${assessment.date.replace(/[^a-zA-Z0-9]/g, "-")}.html`;
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 300);
}

/**
 * Formats structured plain text for the assessment
 */
export function formatAssessmentPlainText(assessment: AssessmentData): string {
  const banner = "=".repeat(64);
  const divider = "-".repeat(64);
  const exportDate = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return `${banner}
GUITAR PRACTICE TRACKER - AI PRACTICE ASSESSMENT REPORT
${banner}
Assessment Date : ${assessment.date}
Recorded Time   : ${assessment.time}
Data Evaluated  : ${assessment.sessionCount !== undefined ? `${assessment.sessionCount} Practice Sessions` : "Full Practice History"}
${divider}

${assessment.analysis}

${divider}
Generated by Guitar Practice Tracker AI Coach
Exported: ${exportDate}
${banner}`;
}

/**
 * Downloads assessment as a formatted .txt text file
 */
export function downloadAssessmentText(assessment: AssessmentData): void {
  const text = formatAssessmentPlainText(assessment);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const filename = `guitar-practice-assessment-${assessment.date.replace(/[^a-zA-Z0-9]/g, "-")}.txt`;
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 300);
}

/**
 * Copies formatted assessment report to clipboard
 */
export async function copyAssessmentToClipboard(assessment: AssessmentData): Promise<boolean> {
  try {
    const text = formatAssessmentPlainText(assessment);
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error("Failed to copy assessment to clipboard:", err);
    return false;
  }
}

/**
 * Directly prints the assessment using DOM portal and @media print styling.
 * This guarantees zero clipping, full multi-page flow, and avoids 0x0 iframe blocking.
 */
export function printAssessmentDirectly(assessment: AssessmentData): Promise<{
  success: boolean;
  blockedBySandbox?: boolean;
}> {
  return new Promise((resolve) => {
    try {
      // 1. Remove any previous portal
      const existing = document.getElementById("print-assessment-portal");
      if (existing) {
        existing.remove();
      }

      // 2. Create the print portal
      const portal = document.createElement("div");
      portal.id = "print-assessment-portal";

      const escapedText = assessment.analysis
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;");

      const printDate = new Date().toLocaleDateString(undefined, {
        year: "numeric",
        month: "long",
        day: "numeric",
      });

      portal.innerHTML = `
        <div style="max-width: 800px; margin: 0 auto; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #0f172a; line-height: 1.6; font-size: 13.5px;">
          <div style="border-bottom: 2.5px solid #4338ca; padding-bottom: 14px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: flex-start;">
            <div>
              <h1 style="font-size: 24px; font-weight: 800; color: #1e1b4b; margin: 0 0 4px 0; letter-spacing: -0.02em;">Guitar Practice Tracker</h1>
              <p style="font-size: 13px; font-weight: 500; color: #475569; margin: 0;">AI Practice Coach Progress Assessment Report</p>
            </div>
            <div style="font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; background: #e0e7ff; color: #3730a3; padding: 4px 12px; border-radius: 9999px; border: 1px solid #c7d2fe;">
              Official Report
            </div>
          </div>

          <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px 16px; margin-bottom: 22px;">
            <div>
              <div style="font-size: 10px; text-transform: uppercase; letter-spacing: 0.06em; font-weight: 700; color: #64748b;">Assessment Date</div>
              <div style="font-size: 14px; font-weight: 700; color: #0f172a; margin-top: 3px;">${assessment.date}</div>
            </div>
            <div>
              <div style="font-size: 10px; text-transform: uppercase; letter-spacing: 0.06em; font-weight: 700; color: #64748b;">Recorded Time</div>
              <div style="font-size: 14px; font-weight: 700; color: #0f172a; margin-top: 3px;">${assessment.time}</div>
            </div>
            <div>
              <div style="font-size: 10px; text-transform: uppercase; letter-spacing: 0.06em; font-weight: 700; color: #64748b;">Practice Data Evaluated</div>
              <div style="font-size: 14px; font-weight: 700; color: #0f172a; margin-top: 3px;">${assessment.sessionCount !== undefined ? `${assessment.sessionCount} Sessions` : "Full History"}</div>
            </div>
          </div>

          <div style="background: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 22px 24px; white-space: pre-wrap; word-wrap: break-word; font-size: 13.5px; line-height: 1.7; color: #1e293b;">${escapedText}</div>

          <div style="margin-top: 32px; padding-top: 14px; border-top: 1px solid #e2e8f0; display: flex; justify-content: space-between; align-items: center; font-size: 11px; color: #94a3b8;">
            <span>Generated by Guitar Practice Tracker AI Coach</span>
            <span>Printed on ${printDate}</span>
          </div>
        </div>
      `;

      document.body.appendChild(portal);
      document.body.classList.add("printing-assessment");

      const cleanup = () => {
        document.body.classList.remove("printing-assessment");
        if (portal.parentElement) {
          portal.parentElement.removeChild(portal);
        }
        window.removeEventListener("afterprint", cleanup);
      };

      window.addEventListener("afterprint", cleanup);

      // Trigger print
      setTimeout(() => {
        try {
          window.print();
          resolve({ success: true });
        } catch (printErr: any) {
          console.warn("Direct window.print() failed (likely sandboxed iframe):", printErr);
          cleanup();
          resolve({ success: false, blockedBySandbox: true });
        }
      }, 80);

      // Failsafe cleanup in case afterprint does not fire
      setTimeout(cleanup, 4000);
    } catch (err) {
      console.error("Print setup error:", err);
      document.body.classList.remove("printing-assessment");
      resolve({ success: false, blockedBySandbox: false });
    }
  });
}

/**
 * Main export for printing assessment report (backwards-compatible)
 */
export async function printAssessmentReport(assessment: AssessmentData): Promise<boolean> {
  const result = await printAssessmentDirectly(assessment);
  return result.success;
}
